source 'https://github.com/CocoaPods/Specs.git'

pod 'MagicalRecord'
pod 'UITableView+NSFetchedResultsController'
pod 'FXForms'
pod 'WAAppRouting'
pod 'WACoreDataSpotlight', :path => '../WACoreDataSpotlight.podspec'